"""add ai coach tracking

Revision ID: 2e2bac33da0f
Revises: e66ea4c936e8
Create Date: 2026-07-03 19:38:14.916616
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e2bac33da0f'
down_revision: Union[str, None] = 'e66ea4c936e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_up_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('added_weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_up_logs_user_id'), 'pull_up_logs', ['user_id'], unique=False)
    op.create_table('wellbeing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellbeing_logs_user_id'), 'wellbeing_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellbeing_logs_user_id'), table_name='wellbeing_logs')
    op.drop_table('wellbeing_logs')
    op.drop_index(op.f('ix_pull_up_logs_user_id'), table_name='pull_up_logs')
    op.drop_table('pull_up_logs')
    # ### end Alembic commands ###

